remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: [Ops Manual]
description: [This is my attempt to condense the advice I've received and experience I've gained over the years into a single place. This is intended entirely for my personal use.]